### ISSUE TITLE
Throwing testtube error within async test creates undefined error.

### ISSUE THREAD

**Issue by DesignerDave** [carbon-io/test-tube#33]
I have the following code:
```
asyncWrapper: (fn) => (_, done) => {
    fn()
      .then(() => done())
      .catch((error) => done(error))
  }

module.exports = o.main({
    _type: testtube.Test,
    name: '<TestName>',
    description: '<description>',
    doTest: asyncWrapper(async () => {
      throw new testtube.errors.SkipTestError('Skipping test because prerequisite test failed.')
    }),
})
```

Whenever the SkipTestError is thrown, I get the following error:
```
 [*] Test: <TestName> (<description>) (1ms)
TypeError: Cannot read property 'bold' of undefined
    at Test._generateReportHelper (/Users/davemccarthy/Repositories/<Project>/node_modules/@carbon-io/test-tube/lib/Test.js:788:38)
    at /Users/davemccarthy/Repositories/<Project>/node_modules/@carbon-io/test-tube/lib/Test.js:798:14
    at arrayEach (/Users/davemccarthy/Repositories/<Project>/node_modules/@carbon-io/test-tube/node_modules/lodash/lodash.js:482:11)
    at Function.forEach (/Users/davemccarthy/Repositories/<Project>/node_modules/@carbon-io/test-tube/node_modules/lodash/lodash.js:7767:11)
    at Test._generateReportHelper (/Users/davemccarthy/Repositories/<Project>/node_modules/@carbon-io/test-tube/lib/Test.js:797:9)
    at /Users/davemccarthy/Repositories/<Project>/node_modules/@carbon-io/test-tube/lib/Test.js:798:14
    at arrayEach (/Users/davemccarthy/Repositories/<Project>/node_modules/@carbon-io/test-tube/node_modules/lodash/lodash.js:482:11)
    at Function.forEach (/Users/davemccarthy/Repositories/<Project>/node_modules/@carbon-io/test-tube/node_modules/lodash/lodash.js:7767:11)
    at Test._generateReportHelper (/Users/davemccarthy/Repositories/<Project>/node_modules/@carbon-io/test-tube/lib/Test.js:797:9)
    at Test.generateReport (/Users/davemccarthy/Repositories/<Project>/node_modules/@carbon-io/test-tube/lib/Test.js:743:12)
    at /Users/davemccarthy/Repositories/<Project>/node_modules/@carbon-io/test-tube/lib/Test.js:217:14
    at /Users/davemccarthy/Repositories/<Project>/node_modules/@carbon-io/test-tube/lib/Test.js:500:11
    at __ (/Users/davemccarthy/Repositories/<Project>/node_modules/@carbon-io/fibers/index.js:92:13)
    at Test.run (/Users/davemccarthy/Repositories/<Project>/node_modules/@carbon-io/test-tube/lib/Test.js:498:14)
    at Test.run (/Users/davemccarthy/Repositories/<Project>/node_modules/@carbon-io/test-tube/lib/Test.js:212:12)
    at Atom._invokeMain (/Users/davemccarthy/Repositories/<Project>/node_modules/@carbon-io/atom/lib/atom.js:631:17)
    at Atom._runMain (/Users/davemccarthy/Repositories/<Project>/node_modules/@carbon-io/atom/lib/atom.js:599:12)
    at Atom._makeObject (/Users/davemccarthy/Repositories/<Project>/node_modules/@carbon-io/atom/lib/atom.js:192:16)
    at Atom.make (/Users/davemccarthy/Repositories/<Project>/node_modules/@carbon-io/atom/lib/atom.js:145:24)
    at Function.o [as main] (/Users/davemccarthy/Repositories/<Project>/node_modules/@carbon-io/atom/lib/atom.js:1121:21)
    at /Users/davemccarthy/Repositories/<Project>/front-end/e2e/<TestSuiteName>.js:10:22
    at fiberFunction (/Users/davemccarthy/Repositories/<Project>/node_modules/@carbon-io/fibers/index.js:225:13)
/Users/davemccarthy/Repositories/<Project>/node_modules/fibers/future.js:313
						throw(ex);
						^
```

Unsure whether or not this has to do with doTest being an async function or not. On test-tube v0.7.4.

**Comment by willshulman** [comment]
We can look into this but I would suggest against using async await with TestTube for mLab. We have much cleaner ways of doing all this. You can ask Greg for help if you don't understand how to use fibers.
